masa-finance/masa-oracle

cmd/masa-node/cli.go, cmd/masa-node/main.go, pkg/constants.go, pkg/pubsub/node_event_tracker.go
main issue is the null pointer on nodeData that doesn't exist for Disconnecting node.
added default RPC_URL to the .env file.
=> 02 07 testnet bug fixes

README.md, pkg/constants.go
Maybe we should go back to including this list in the repo as a config.json file somewhere again.
We might also consider publishing the list at a static URL that nodes can request on bootup given their network (ENV).
=> updating readme with list of bootnodes. 

cmd/masa-node/cli.go, pkg/oracle_node.go, pkg/pubsub/node_data.go, pkg/pubsub/node_event_tracker.go
=> Fix timing issues for nodes

Dockerfile, docker-compose.yaml
Just updates Docker to work in a more straightforward way with the operator's env file (just copy to container).
=> just copy .env to the container

docs/oracle-node/introduction.md, docs/validator-node/introduction.md, docs/worker-node/introduction.md
docs repo cant build because of those equal signs: https://vercel.com/masa-finance/masa-docs/DB3wyuBXmKqEj1ZZjCLJPqSk1YyC?filter=errors
=> fix: remove ======= from md metadata because it causes docs to crash

.github/dependabot.yml
=> chore: remove core team from dependabot reviewers

.github/release.yml
related to https://github.com/masa-finance/masa-oracle/issues/393
Bittensor similar ticket: https://github.com/masa-finance/masa-bittensor/issues/83
Adds github configuration to generate release notes automatically from labels in the PR
=> github: add release-notes configuration

.github/workflows/commitlint.yaml
This adds a pipeline running opensource-nepal/commitlint for checking commits are following conventional commits before merging a PR. 
https://www.conventionalcommits.org/en/v1.0.0/
In scope of #393
=> ci: add commitlint workflow

pkg/api/handlers_node.go, pkg/db/operations.go, pkg/workers/workers.go
Enhance Robustness of MonitorWorkers Function with Nil Checks & Refctor
This closes #410 
This PR introduces a series of enhancements to the `MonitorWorkers` function within the `workers.go` file, aimed at improving the robustness and reliability of the function. The primary focus of these changes is to prevent runtime errors caused by nil pointer dereferences, which were identified as a potential issue in the existing implementation as outlined in #410 . Additionally, the PR includes refactoring to improve code readability and maintainability without altering the core functionality of the function.
1. **Nil Checks:** Added comprehensive nil checks at the beginning of the `MonitorWorkers` function to ensure that none of the critical components, `node.ActorRemote`, or …
=> fix: error handling in `MonitorWorkers`

pkg/api/handlers_node.go, pkg/db/operations.go, pkg/workers/workers.go
This closes #408 
This PR addresses a critical bug in the `SendWork `function within the `workers.go` file, where a nil pointer dereference panic occurs under certain conditions. The issue was identified in the remote worker spawning logic, specifically when the `SpawnNamed` method returns a nil PID `*actor.PID`, and subsequent operations attempt to use this nil pointer, leading to a runtime panic.
- **Nil Check for `spawnedPID`**: Added a nil check immediately after attempting to spawn a new actor with `SpawnNamed`. If `spawnedPID` is nil, the function logs an error and returns early from the goroutine, preventing the nil pointer dereference.
- **Correct Loop Variable Capture**: Modified the anonymous goroutine function within the loop to take the loop variable [p] as a parameter. This …
=> fix: better error handling in `SendWork`

pkg/network/address.go, pkg/oracle_node.go
This PR fixes #439 
Currently the private ip address of a node can find its way into the node data. The node data is used to filter through validators and workers and this requires the public ip to always be stored in the node data for processing.
=> fix: private ip address issue in node data

pkg/workers/workers.go
This PR fixes # was improperly checking a bool val during send work which would try to send work to oracles not just worker nodes 
=> fix: fixed p checks on sendwork

.gitignore, pkg/db/resolver_cache.go, pkg/oracle_node_listener.go
This PR addresses potential nil pointer dereference errors in the handling of the DHT (Distributed Hash Table) object within our network package. By ensuring that the `kademliaDHT` object is properly checked for `nil` before usage, we prevent runtime panics that could occur due to nil pointer dereferences. This enhances the robustness and reliability of our DHT operations, particularly during the bootstrap process and when interacting with the DHT for data retrieval and publishing.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x991 pc=0x1053e7900]
goroutine 2425 [running]:
github.com/libp2p/go-libp2p-kad-dht.(*IpfsDHT).PutValue(0x0, {0x106182ea0, 0x107777240}, {0x14001944340, 0x39}, {0x14002628200, 0x1f6, …
```
=> fix: Nil Pointer Dereference Errors in DHT Initialization and Usage

.github/workflows/release.yaml
This PR fixes the binary built by the github action for use by the gcp based protocol nodes so that it includes the VERSION from git tags
=> fix workflow to build binary with VERSION from git

pkg/workers/worker_manager.go, pkg/workers/worker_selection.go, twitter_cookies.example.json
Our system was inefficiently utilizing available workers, often failing after attempting only a single remote worker if they had incorrectly setup Twitter credentials for example. This led to failure of requests if a single worker had a client side error.
We've improved the worker selection process to attempt connections with all eligible remote workers before falling back to local execution. currently 10 workers will be attempted.
This has not been tested in a large network of workers where there are multiple faulty worker nodes that need to be attempted. This requires a more elegant approach as outlined here where reliability and other factors are considered: https://github.com/masa-finance/masa-oracle/issues/544
This change has been tested in a production environment with multiple …
=> feat(workers): enhance error handling and worker selection in DistributeWork

.github/workflows/tests.yaml
This PR generates coverage files from test runs and upload these to codecov
=> chore(ci): export coverage to codecov

.github/workflows/goreleaser.yml
This PR fixes the goreleaser failing during tags. 
```
• took: 12m26s
• generating changelog
⨯ release failed after 12m26s              error=POST https://api.github.com/repos/masa-finance/masa-oracle/releases/generate-notes: 403 Resource not accessible by integration []
Error: The process '/opt/hostedtoolcache/goreleaser-action/2.3.2/x64/goreleaser' failed with exit code 1
```
=> chore(ci): fixup goreleaser permissions

cmd/masa-node/config.go, node/blockchain.go, node/options.go, node/oracle_node.go, pkg/chain/block.go, pkg/chain/block_test.go, pkg/chain/chain.go, pkg/chain/chain_suite_test.go, pkg/chain/pos.go, pkg/chain/pos_test.go, pkg/pubsub/manager.go, pkg/tests/integration/blockchain_test.go, pkg/tests/integration/tracker_test.go
Previously the blockchain data was treated as an empty struct - `struct {}`. That basically meant that we were discarding _any_ content from the blockchain event channels and just keeping data around in the persistent layer.
This PR aims to fix that, and on top adds unit tests and integration tests:
- It tries to cover the `chain` package and `pos` package introducing a simple test batch
- It adds an integration test to make sure the data emitted in the blockchain is correctly propagated between nodes
=> fix(blockchain): be more strict on blockchain data

Makefile, cmd/masa-node/main.go, pkg/config/app.go, pkg/config/constants.go
This PR a new feature that allows the API server to be conditionally enabled or disabled based on configuration. The changes include:
1. In cmd/masa-node/main.go:
- Refactored signal handling into a separate function `handleSignals`
- Added conditional logic to start the API server only if enabled
- Improved logging to indicate API server status
2. In pkg/config/app.go:
- Added `APIEnabled` field to the `AppConfig` struct
- Set default value for `APIEnabled` to false in `setDefaultConfig`
- Added command-line flag for `apiEnabled` in `setCommandLineConfig`
3. In pkg/config/constants.go:
- Added `APIEnabled` constant for environment variable configuration
These changes provide more flexibility in node configuration, allowing users to run the node with or without the API server. This can be …
=> feat(api): Add configurable API server enablement

internal/versioning/version.go, pkg/pubsub/node_data.go, pkg/pubsub/node_event_tracker.go, pkg/scrapers/twitter/config.go, pkg/scrapers/twitter/followers.go, pkg/scrapers/twitter/profile.go, pkg/scrapers/twitter/tweets.go, pkg/workers/config.go, pkg/workers/worker_manager.go, pkg/workers/worker_selection.go
This PR implements an improved worker selection algorithm for Twitter tasks in the Masa Oracle project. The goal is to balance between prioritizing high-performing workers and ensuring fair work distribution.
- Now uses a specialized selection process for the Twitter category (`pubsub.CategoryTwitter`)
- Maintains existing behavior for all other worker categories
- Selects a larger pool of top-performing nodes
- Introduces controlled randomness by shuffling the pool of top performers
- Creates Worker objects from the shuffled pool, respecting the original limit
- Determines the optimal pool size as the maximum of:
- 5 (minimum pool size)
- Double the requested limit
- 20% of total nodes
- Sorts nodes based on their Twitter reliability using multiple criteria:
1. More recent last returned …
=> feat(twitter): Enhanced Twitter Worker Selection Algorithm

pkg/scrapers/twitter/auth.go, pkg/scrapers/twitter/config.go
This PR introduces improvements to our Twitter scraping authentication process to make it more robust and less detectable as automated behavior.
1. In `config.go`:
- Introduced `RandomSleep()` function to add variability in request timing
- Set sleep duration range from 500ms to 2s
- Initialized a package-level random number generator for thread-safety
2. In `auth.go`:
- Updated `NewScraper()` to use `RandomSleep()` before and after login attempts
- Improved error handling and logging in the login process
These changes aim to make our scraping behavior more human-like and reduce the risk of being detected as a bot or having our accounts suspended. By introducing random delays between actions, we mimic natural user behavior more closely.
- Tested login process with multiple accounts
- …
=> feat(twitter): Implement random sleep and improve login process

pkg/staking/config.go, pkg/staking/config_test.go, pkg/tests/scrapers/twitter_scraper_test.go, pkg/tests/twitter/twitter_scraper_test.go
There was still some code reading from the filesystem instead of the embedded files in the binary.
Regression introduced in https://github.com/masa-finance/masa-oracle/pull/523.
Fixes: https://github.com/masa-finance/masa-oracle/issues/578
It also adds a simple unit test to check whether we can read from the embedded contracts.
See also: https://github.com/masa-finance/masa-oracle/pull/579
=> fix(contracts): load config from embedded

pkg/api/config.go, pkg/workers/config.go, pkg/workers/worker_manager.go
This pull request includes several changes to the configuration and handling of worker timeouts and peer discovery in the `pkg/api/config.go` and `pkg/workers` files. The most important changes are summarized below.
Configuration updates:
* [`pkg/api/config.go`](diffhunk://#diff-ae0afc2c35419636d0ebfb49cf74dda4544e535a112c222b17a6c301cbe4bfd1L12-R12): Increased `WorkerResponseTimeout` in `APIConfig` from 60 seconds to 120 seconds.
* [`pkg/workers/config.go`](diffhunk://#diff-5c1a5ce2f866633ea097d20d0c47a0225f715667d150053224a1b7a456d173b4R13-R28): Added a new `FindPeerTimeout` field to `WorkerConfig` and updated default values for several timeout-related fields.
Peer discovery improvements:
* [`pkg/workers/worker_manager.go`](diffhunk://#diff-1afd3fed6e81b9a9733b508a9a6b5be …
=> feat: worker selection tuning

cmd/masa-node/main.go, node/options.go, node/oracle_node.go, node/oracle_node_listener.go, node/protocol.go, pkg/config/app.go, pkg/config/config_suite_test.go, pkg/config/config_test.go, pkg/config/options.go, pkg/network/kdht.go, pkg/pubsub/manager.go, pkg/pubsub/node_event_tracker.go, pkg/tests/integration/tracker_test.go, pkg/tests/node_data/node_data_tracker_test.go, pkg/workers/handlers/web.go, pkg/workers/types/work_types.go, pkg/workers/worker_manager.go
After #623, #625 and #626, this is the final cleanup step. Our code is now singleton-free, and the circular dependencies that prevented us from moving Options processing to the `config` package are no more.
Die, singletons, die!!!!!
=> chore(cleanup): Finish removing the AppConfig singleton and move Options processing to the config package

.github/workflows/images.yml
This PR fixes https://github.com/masa-finance/masa-oracle/issues/396
=> chore(ci): add GHA pipeline to publish container images

Dockerfile, docker-compose.yaml
Fixes:
```
#20 CACHED
#21 [linux/arm64 base 7/7] COPY --chown=masa:masa .env .
#21 ERROR: failed to calculate checksum of ref s71w92flz0ldd9l9jgytucp8r::835vi4nvw90awwkc3l6bvbeqe: "/.env": not found
```
This pull request includes changes to the `Dockerfile` and `docker-compose.yaml` to improve the configuration and startup process for the application. The most important changes include modifying the command in the `Dockerfile` to adjust the `--validator` flag (this was causing the container to not start) and updating the `docker-compose.yaml` to mount the `.env` file as a volume.
Configuration and startup improvements:
* [`Dockerfile`](diffhunk://#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L36-R41): Modified the `CMD` instruction to adjust the …
=> fix(ci): do not bundle .env file while building the image

pkg/config/app.go, pkg/config/constants.go
This PR fixes # the handling of the privateKeyFile and api-enabled options.
privateKeyFile wasn't being correctly processed if the masaDir was changed
api-enabled should use the constant defined for that purpose instead of inlining the value
=> fix: Fix handling of the privateKeyFile and api-enabled options

docs/docs.go, pkg/api/handlers_data.go, pkg/api/routes.go, pkg/scrapers/twitter/tweets.go, pkg/workers/handlers/twitter.go, pkg/workers/types/work_types.go, pkg/workers/worker_manager.go
This PR adds support for getting a tweet by id.  It exposes `v1.POST("/data/twitter/tweets/:id", API.SearchTweetById())` which leverages the `scraper.GetTweet(id)` method of `github.com/imperatrona/twitter-scraper`.
The necessary data_types are also added, adding `TwitterTweet            WorkerType = "twitter-tweet"`
=> feat: tweet by id support
