README.md, cmd/masa-node/cli.go, cmd/masa-node/main.go, pkg/constants.go, pkg/pubsub/node_event_tracker.go
=> Bugfixes to testnet

README.md, node-install.sh
minor update some copy about masa node and network on README (typo fix)
=> copy update for README

pkg/constants.go
bumping up the version to reset the network
=> bump version to reset network

.github/workflows/release.yaml, README.md, pkg/constants.go
clear out old nodedata by bumping up version of network
=> bump version of the network up

pkg/constants.go
Let's bump the network to a new version to try with updates to timing / buffering of connection status.
=> bump to version 8

cmd/masa-node/main.go
Running this through to investigate issue with bootnodes booting up
=> add some logging to investigate config issue in gcp bootnodes

pkg/api/routes.go
solved path finding for html templates
=> fixed path for binary build for html templates

pkg/api/routes.go
=> using embed for static html files path

Dockerfile, cmd/masa-node/main.go, pkg/api/routes.go, pkg/config/app.go, pkg/config/welcome.go, pkg/db/resolver_cache.go
disable monitoring node data and added --cachePath to cli
=> Bug fix boot

pkg/llmbridge/client.go, pkg/llmbridge/payload.go
Made changes to the sentiment prompt and wanted to demonstrate the change I made and testing locally,  This seems to provide a better summary output.
Original prompt:
"Please analyze the sentiment of the following tweets without bias and summarize the overall sentiment:",
New prompt:
"Please perform a sentiment analysis on the following tweets, using an unbiased approach. Sentiment analysis involves identifying and categorizing opinions expressed in text, particularly to determine whether the writer's attitude towards a particular topic, product, etc., is positive, negative, or neutral. After analyzing, please provide a summary of the overall sentiment expressed in these tweets, including the proportion of positive, negative, and neutral sentiments if applicable.",
Original Summary: …
=> modified sentiment prompt for llms

cmd/masa-node/main.go, pkg/api/handlers_node.go, pkg/workers/workers.go
fixed worker response when base64 vs json
=> fixed worker response when base64 vs json

DOCKER.md, docker-compose.yaml
A few updates to the docker instructions for running a local masa protocol node
=> Updates to docker instructions

DOCKER.md, README.md
This adds a section on hardware requirements and clarifies the difference between setting up with Docker (Quick Start) versus building locally, and rearranges the table of contents.
=> Updates to README.md (add hardware requirements, rearrange contents)

.github/ISSUE_TEMPLATE/feature_request.md
This adds templates for opening feature requests issues
=> github: Add feature request template

.github/ISSUE_TEMPLATE/bug_report.md
Adding templates for opening bug reports
=> github: Add template for bug reports

.github/ISSUE_TEMPLATE/config.yml
This adds some options when creating new issues (and avoids to skip templates ;) )
=> github: create issue configuration

pkg/api/handlers_node.go, pkg/db/operations.go, pkg/workers/workers.go
This pull request addresses a critical issue where a nil pointer dereference leads to a panic crash in the `updateRecords` function within the `workers` package. The crash occurs under certain conditions when attempting to send node data records, as indicated by the provided stack trace in https://github.com/masa-finance/roadmap/issues/46. This fix ensures that the application gracefully handles scenarios where it encounters nil pointers, thus improving the stability and reliability of the Masa Oracle Node.
The panic is triggered by a nil pointer dereference, as indicated by the `SIGSEGV` segmentation violation signal. The stack trace points to the `updateRecords` function in `workers.go` as the source of the panic. After a thorough review, it was determined that the function does not …
=> fix: nil pointer dereference in updateRecords function

.github/workflows/secscan.yml
This PR adds the secscan pipeline to our workflow - hopefully trying to catch up bugs earlier than later :)
=> ci: add secscan

.gitignore, cmd/masa-node-cli/components.go, pkg/config/constants.go, pkg/db/operations.go, pkg/workers/workers.go
This PR fixes missing version string in constants file and some messaging changes.
=> fix: messaging and version string in constants

cmd/masa-node/main.go, pkg/network/address.go, pkg/oracle_node.go, pkg/oracle_node_listener.go, pkg/pubsub/public_key_topic.go, pkg/scrapers/web/web.go, pkg/workers/workers.go
This PR fixes # worker ch should never be nil 
=> fix: workerch nil race condition

pkg/oracle_node_listener.go, pkg/pubsub/node_event_tracker.go, pkg/workers/handler.go, pkg/workers/workers.go
This PR fixes # fixed hang on a remote future deadletter when a worker has left the network but kd and node data had not yet updated
=> fix: remote future deadletter issue

pkg/workers/workers.go
=> chore: clean up commented code and logging

pkg/workers/handler.go, pkg/workers/workers.go
This PR fixes # updating err messaging to user console logs
=> chore: updating err messaging to user console logs

cmd/masa-node-cli/handlers.go, cmd/masa-node/staking.go, cmd/tagger/main.go, pkg/api/handlers_data.go, pkg/api/handlers_node.go, pkg/chain/block.go, pkg/consensus/signer.go, pkg/db/operations.go, pkg/db/resolver_cache.go, pkg/masacrypto/cert_test.go, pkg/masacrypto/key_manager.go, pkg/network/discover.go, pkg/oracle_node.go, pkg/oracle_node_listener.go, pkg/pubsub/manager.go, pkg/pubsub/worker_tracker.go, pkg/scrapers/twitter/auth.go, pkg/scrapers/twitter/tweets.go, pkg/scrapers/web/web.go, pkg/staking/approve.go, pkg/staking/contracts.go, pkg/staking/faucet.go, pkg/staking/stake.go, pkg/staking/verify.go, pkg/tests/auth_test.go, pkg/tests/scrape_test.go, tools/abigen_helper.go
This PR fixes # fixed panic bug on remove node data on invalid stream write
=> fix: panic on remove node data 

pkg/oracle_node.go
This PR fixes # handle all types of data for block event
=> fix: handle all types of data for block event

cmd/masa-node-cli/handlers.go, cmd/masa-node/main.go, pkg/api/handlers_data.go, pkg/api/routes.go, pkg/chain/block.go, pkg/chain/chain.go, pkg/config/app.go, pkg/consensus/signer.go, pkg/db/operations.go, pkg/db/resolver_cache.go, pkg/llmbridge/sentiment.go, pkg/masacrypto/keys.go, pkg/network/discover.go, pkg/network/kdht.go, pkg/oracle_node.go, pkg/oracle_node_listener.go, pkg/pubsub/manager.go, pkg/pubsub/node_event_tracker.go, pkg/scrapers/web/web.go, pkg/workers/client.go, pkg/workers/handler.go, pkg/workers/workers.go
This PR fixes # added get block by hash api/v1/blocks/:hash and documenting blockchain funcs and testing blockevent types
=> chore: added get block by hash api and func documenting

Makefile
This PR fixes # updated makefile
=> fix: updated makefile

.github/workflows/release.yaml
This PR fixes the workflow not checking out with tags
=> ci: fix workflow to build binary with VERSION from git -- fetch_depth: 0

.github/workflows/build.yaml, .github/workflows/release.yaml
This PR centralize building of the oracle by using `make build` also in the CI steps - no reason to scatter the logic across multiple places.
=> chore(ci): be consistent and centralize building logic

docs/docs.go, pkg/api/handlers_data.go, pkg/scrapers/discord/getchannelmessages.go, pkg/workers/handler.go, pkg/workers/workers.go
This PR adds functionality to the Discord messages scraping. It extends the options for parameters than can be submitted and utilized to specify how many messages to scrape and to scrape messages `before` a certain message ID.
Here is the relevant [documentation](https://discord.com/developers/docs/resources/message#get-channel-messages) as we may want to extend this in the future.
@nolanjacobson please look this over to ensure it doesn't affect features you implemented and that default values will be used if no input is give.  These parameters should be optional.
Also, if you want to try the functionality these changes were built for the scraper being merged in [this PR](https://github.com/masa-finance/awesome-masa/pull/2) but can be utilized within that branch.  Check the readme for …
=> feat: discord messages upgrade

Makefile, cmd/masa-node-cli/components.go, cmd/masa-node/main.go, internal/versioning/version.go, pkg/config/app.go, pkg/config/version.go, pkg/config/welcome.go, pkg/oracle_node.go, pkg/pubsub/node_data.go
This PR fixes https://github.com/masa-finance/masa-oracle/issues/499
The changes here splits the version into two components, an `application` version and a `protocol version`. 
The current problem is that we have a single version that is also used by the network to identify old nodes and forbid interaction. bootnodes use that for instance to gate new clients, and as such it would refuse to process old versions of the application.
So, if we have a new release out - even if it does not have any changes at libp2p protocol level, is used to distinguish and forbid users to join the network. 
Note: it also moves `pkg/version` back to `internal/versioning` - no need to make the versions importable from outside.
The current changes splits the version in …
=> feat(versioning): split application and protocol versioning

docs/oracle-node/telegram-sentiment.md
This PR fixes #
Updates to docs in telegram sentiment to replace twitter nomenclature
=> chore: updates to docs

cmd/masa-node/main.go, go.mod, pkg/config/app.go, pkg/config/options.go, pkg/network/kdht.go, pkg/oracle_node.go, pkg/pubsub/manager.go, pkg/pubsub/node_data.go, pkg/pubsub/public_key_topic.go, pkg/tests/integration/oracle_suite_test.go, pkg/tests/integration/tracker_test.go
This PR is just a step ahead towards having a small smoke test suite #367 .
Currently it behaves more as an integration test - but I'd like to start extracting some of the logics so can be re-used across tests.
=> feat(tests): add baseline for an integration test

pkg/network/kdht.go, pkg/oracle_node.go, pkg/pubsub/node_data.go
This fixes regressions in tests introduced in https://github.com/masa-finance/masa-oracle/pull/524
=> chore: revert back changes to fix integration tests

internal/versioning/version.go
This PR bumps the protocol version to `v0.7.0` as we are about to cut the release out ( https://github.com/masa-finance/roadmap/issues/79 ) 
=> chore: bump protocol version to `v0.7.0`

.github/workflows/secscan.yml
https://github.com/securego/gosec/issues/1220
This PR fixes CI runs currently failing (see e.g. https://github.com/masa-finance/masa-oracle/actions/runs/10906050059/job/30266386048?pr=523 )
=> chore(secscan): pin version

go.mod, go.sum, pkg/event/config.go, pkg/scrapers/twitter/cookies.go, pkg/scrapers/twitter/tweets.go
=> feat (twitter) scraper and user agent hot fix

.gitignore, internal/versioning/version.go, pkg/pubsub/node_data.go, pkg/pubsub/node_event_tracker.go, pkg/tests/node_data/node_data_suite_test.go, pkg/tests/node_data/node_data_test.go, pkg/tests/node_data/node_data_tracker_test.go, pkg/workers/config.go, pkg/workers/worker_manager.go, pkg/workers/worker_selection.go
Our current worker selection mechanism for Twitter tasks doesn't account for worker reliability and availability. This leads to inefficient task distribution, where unreliable or frequently unavailable workers may be selected, causing delays and failures in task execution. We need a more intelligent selection process that prioritizes workers based on their past performance and availability.
We're implementing a priority-based worker selection mechanism for Twitter tasks. This new system will track worker performance metrics and availability, using this data to prioritize more reliable and available workers. For other task types, we'll maintain the existing round-robin selection to avoid potential regression.
- Added new performance metric fields to `NodeData` struct in `node_data.go`:
- …
=> Feat(workers) implement adaptive worker selection for improved task distribution

.env.example
This pull request includes a small change to the `.env.example` file. The change modifies the Twitter configuration to use `TWITTER_ACCOUNTS` instead of `TWITTER_USERNAME` (old). So it is consistent with docs as well: https://developers.masa.ai/docs/masa-protocol/protocol-twitter-scraper-config
* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL26-R26): Changed `TWITTER_USERNAME` to `TWITTER_ACCOUNTS` to better reflect that multiple accounts can be configured.
=> chore(docs): update .env.example

pkg/api/handlers_node.go
This PR fixes incorrect returned totalPages
=> fix: incorrect returned totalPages

pkg/event/config.go, pkg/event/event.go, pkg/event/event_client.go, pkg/scrapers/twitter/account.go, pkg/scrapers/twitter/auth.go, pkg/scrapers/twitter/common.go, pkg/scrapers/twitter/followers.go, pkg/scrapers/twitter/profile.go, pkg/scrapers/twitter/scraper.go, pkg/scrapers/twitter/tweets.go, pkg/tests/scrapers/twitter_scraper_test.go, pkg/tests/twitter/twitter_scraper_test.go, pkg/workers/handlers/twitter.go, pkg/workers/types/login_event.go, pkg/workers/types/request_response.go, pkg/workers/worker_manager.go
This commit introduces several enhancements and new features related to handling login events and worker responses in the masa-oracle project.  Details:  
New Functionality: 
- Added SendLoginEvent method in EventClient to send login events to the server.
- Introduced LoginEvent handling in WorkHandlerManager to track and send login events received from workers.
Enhancements:  
- Improved error handling and logging in HandleWorkerStream method to ensure proper tracking and reporting of errors during worker communication.
- Enhanced ScrapeFollowersForProfile function in the Twitter scraper to return login events.
Code Refactoring:  
- Refactored WorkResponse struct to include LoginEvent field so that we can handle that in the code where the peerId is available.
-  Updated …
=> feat: login event 0.8.9
